version: '3.8'

services:
  nginx:
    depends_on:
      - frontend
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./
    ports:
      - "80:80"
    volumes:
       - trustbadge:/trustbadge

  parser:
    build:
      dockerfile: Dockerfile
      context: "./parser"
    volumes:
      - /app/node_modules
      - ./parser:/app/parser
    ports:
      - "3001:3001"

  frontend:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile
      context: ./frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app/frontend
    ports:
      - "3000:3000"

  backend:
    build:
      dockerfile: Dockerfile
      context: ./backend
    command: python src/main.py
    volumes:
      - ./backend:/app

  searx:
    image: searx/searx
    ports:
      - "8080:8080"

  trustbadge:
    build:
      dockerfile: Dockerfile
      context: "./trustbadge-script"
    volumes:
      - trustbadge:/app/dist
volumes:
  trustbadge:
